add commented mypy and fix python

diff --git a/.github/workflows/service-build-test-upload.yml b/.github/workflows/service-build-test-upload.yml
--- a/.github/workflows/service-build-test-upload.yml
+++ b/.github/workflows/service-build-test-upload.yml
@@ -102,7 +102,7 @@ jobs:
       - name: Run black
         if: steps.changed-py-files.outputs.any_changed == 'true'
         run: |
-          docker run --entrypoint "" ${{ env.IMAGE_NAME }} black --target-version py310 -S --check /usr/src/app
+          docker run --entrypoint "" ${{ env.IMAGE_NAME }} black --target-version py39 -S --check /usr/src/app
 
       - name: Run isort
         if: ${{ steps.changed-py-files.outputs.any_changed == 'true' && success() || failure() }}
@@ -113,6 +113,12 @@ jobs:
         if: ${{steps.changed-py-files.outputs.any_changed == 'true' && success() || failure() }}
         run: |
           docker run --entrypoint "" ${{ env.IMAGE_NAME }} flake8 ${{ steps.changed-py-files.outputs.all_changed_files }}
+
+      # TODO: fix all issues and return
+      # - name: Run mypy
+      #   if: ${{ steps.changed-py-files.outputs.any_changed == 'true' && success() || failure() }}
+      #   run: |
+      #     docker run --entrypoint "" ${{ env.IMAGE_NAME }} mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --follow-imports=silent
 
       - name: Run tests
         if: success()
